### ISSUE TITLE
`extends` requires target to be JSON/JS

### ISSUE THREAD

**Issue by divmain** [walmartlabs/eslint-config-defaults#32] opened 2015-08-31 01:25 UTC
After the 5.0 YAML change, things are broke.  More specifically, when specifying `extends: "eslint-config-defaults/configurations/walmart/es6-node.yaml"`, ESlint will always treat the target as a JS module (see [here](https://github.com/eslint/eslint/blob/master/lib/config.js#L81) and [here](https://github.com/eslint/eslint/blob/master/lib/config.js#L113)).  This worked with JSON because `require("path/to/json/file.json")` works in Node.

This seems a limitation in ESlint itself, and should be fixed there.  But adding this here for now while I'm thinking of it.

Short term solution would be to revert to JSON, or to instruct users to stick to `4.x.x` package versions until things are worked out.

**Comment by baer** [comment] 2015-09-01 07:18
Oooof confirmed - this is true. However, oddly I was able to run a global ESLint that pointed to the YAML in this directory and it did work. I am reverting, deprecating and revving since it seems like the bast plan until ESLint is sorted out.

**Comment by baer** [comment] 2015-10-01 23:06
Closed in #33

**Closed by baer** 2015-10-01 23:06 UTC
Labels: bug

**Comment by hax** [comment] 2015-11-17 09:40
Still not fixed?
